CREATE TABLE EMPLOYEES (ID INTEGER NOT NULL, "NAME" VARCHAR(255), ROLE_ID INTEGER, PRIMARY KEY (ID));

CREATE TABLE ROLES (ID INTEGER NOT NULL, "NAME" VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE TASKS (ID INTEGER NOT NULL, DESCRIPTION VARCHAR(255), EMPLOYEE_ID INTEGER, PRIMARY KEY (ID));


Alter Table ROOT.EMPLOYEES
Add FOREIGN KEY (ROLE_ID)
References ROOT.ROLES (ID);   

Alter Table ROOT.TASKS
Add FOREIGN KEY (EMPLOYEE_ID)
References ROOT.EMPLOYEES (ID) 
ON DELETE CASCADE;

CREATE SEQUENCE employee_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE role_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE task_seq START WITH 1 INCREMENT BY 1;